name: Build and Deploy Vue App

on:
  push:
    branches:
      - actions # Nasłuchuje zmian w branchu "actions"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Sprawdzenie kodu
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Ustawienie Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalacja zależności
      - name: Install dependencies
        run: npm install

      # 4. Budowanie aplikacji
      - name: Build project
        run: npm run build

      # 5. Deploy na GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist