name: Deploy Vue App

on:
  push:
    branches:
      - actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # sprawdzanie kodu repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Zainstaluj Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Wersja Node.js zgodna z projektem

      # Instalacja zależności
      - name: Install dependencies
        run: npm install

      # Uruchom budowanie aplikacji
      - name: Build project
        run: npm run build

      # Deploy na GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist